"""Solucionado error en la ruta de confirmación de cambio de contraseña

Revision ID: 255d8eca9476
Revises: 40d48ca1a569
Create Date: 2026-07-29 19:15:57.610567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255d8eca9476'
down_revision: Union[str, Sequence[str], None] = '40d48ca1a569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
