"""Restricción en propiedad dni de trabajadores para que tengan 8 dígitos y 1 letra

Revision ID: 33a3ff12e090
Revises: ca143b96b9bf
Create Date: 2026-09-03 16:52:18.638471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a3ff12e090'
down_revision: Union[str, Sequence[str], None] = 'ca143b96b9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trabajadores', 'nif_nie',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trabajadores', 'nif_nie',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
