"""Actualización para la confirmación de cambio de contraseña validando el código de 6 dígitos enviado al email

Revision ID: 40d48ca1a569
Revises: 711e1e4ada28
Create Date: 2026-07-29 19:03:25.454704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d48ca1a569'
down_revision: Union[str, Sequence[str], None] = '711e1e4ada28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('codigo_recuperacion', sa.String(length=10), nullable=True))
    op.add_column('usuarios', sa.Column('codigo_expira_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'codigo_expira_at')
    op.drop_column('usuarios', 'codigo_recuperacion')
    # ### end Alembic commands ###
