"""Asegurar ondelete restrict en fichajes y correcciones

Revision ID: 4d5bdf6e6df7
Revises: 9e53143a9d0c
Create Date: 2026-09-10 10:59:35.105394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5bdf6e6df7'
down_revision: Union[str, Sequence[str], None] = '9e53143a9d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('correcciones_fichaje', 'tipo_evento_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('fichajes', 'tipo_evento_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fichajes', 'tipo_evento_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('correcciones_fichaje', 'tipo_evento_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
