"""Actualización del código de core/database

Revision ID: 50842cc74af8
Revises: 85e148bb9f29
Create Date: 2026-07-21 12:34:05.989539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50842cc74af8'
down_revision: Union[str, Sequence[str], None] = '85e148bb9f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'v_fichajes_vigentes',
        'Fichajes con efecto legal actual: excluye los anulados (vía correcciones_fichaje aprobadas) y los ya sustituidos por una fila más reciente. Es la vista que deben usar nómina, informes e inspección; nunca se borra ni edita la fila original.',
        existing_comment='Fichajes con effecto legal actual: excluye los anulados (vía correcciones_fichaje aprobadas) y los ya sustituidos por una fila más reciente.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'v_fichajes_vigentes',
        'Fichajes con effecto legal actual: excluye los anulados (vía correcciones_fichaje aprobadas) y los ya sustituidos por una fila más reciente.',
        existing_comment='Fichajes con efecto legal actual: excluye los anulados (vía correcciones_fichaje aprobadas) y los ya sustituidos por una fila más reciente. Es la vista que deben usar nómina, informes e inspección; nunca se borra ni edita la fila original.',
        schema=None
    )
    # ### end Alembic commands ###
