"""Propiedad añadida al modelo de correcciones de fichaje para que guarde el id del tipo de evento de fichaje correspondiente, relación arreglada

Revision ID: 598cddfe82cc
Revises: bdb183d5018f
Create Date: 2026-08-27 18:33:10.523710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598cddfe82cc'
down_revision: Union[str, Sequence[str], None] = 'bdb183d5018f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('correcciones_fichaje_tipo_evento_id_fkey', 'correcciones_fichaje', 'tipos_evento_fichaje', ['tipo_evento_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('correcciones_fichaje_tipo_evento_id_fkey', 'correcciones_fichaje', type_='foreignkey')
    # ### end Alembic commands ###
