"""Añadido modelo de licencias para control de registro de empresas mediante licencia de suscripción de la aplicación

Revision ID: 68b56a04774d
Revises: 9a3f67a97dc6
Create Date: 2026-09-09 19:10:00.494602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b56a04774d'
down_revision: Union[str, Sequence[str], None] = '9a3f67a97dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
