"""Nuevos cambios en algunos modelos

Revision ID: 7938699dbe31
Revises: f7c8d9e0a1b2
Create Date: 2026-09-14 19:50:22.345261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7938699dbe31'
down_revision: Union[str, Sequence[str], None] = 'f7c8d9e0a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('correcciones_fichaje', 'firma_solicitante',
               existing_type=sa.TEXT(),
               comment='Ruta de la firma digital de quien solicita la corrección.',
               existing_nullable=True)
    op.alter_column('correcciones_fichaje', 'firma_resolutor',
               existing_type=sa.TEXT(),
               comment='Ruta de la firma digital de quien resuelve la corrección.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('correcciones_fichaje', 'firma_resolutor',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ruta de la firma digital de quien resuelve la corrección.',
               existing_nullable=True)
    op.alter_column('correcciones_fichaje', 'firma_solicitante',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Ruta de la firma digital de quien solicita la corrección.',
               existing_nullable=True)
    # ### end Alembic commands ###
