"""Nuevos campos de cambio de email en usuarios

Revision ID: 7a5962b45679
Revises: 7938699dbe31
Create Date: 2026-09-15 12:19:45.013867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5962b45679'
down_revision: Union[str, Sequence[str], None] = '7938699dbe31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email_pendiente_verificacion', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('token_cambio_email', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('token_cambio_email_expira_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['token_cambio_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'token_cambio_email_expira_at')
    op.drop_column('usuarios', 'token_cambio_email')
    op.drop_column('usuarios', 'email_pendiente_verificacion')
    # ### end Alembic commands ###
