"""Modelo tipos de evento de fichaje asociado a la empresa

Revision ID: 7f2ca16c0841
Revises: cf553310ffe5
Create Date: 2026-08-14 12:00:54.135485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2ca16c0841'
down_revision: Union[str, Sequence[str], None] = 'cf553310ffe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fichajes', 'tipo_evento_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='tipo_evento_id::text::uuid') # <--- Añade esta línea
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tipos_evento_fichaje_empresa_id_fkey', 'tipos_evento_fichaje', type_='foreignkey')
    op.drop_column('tipos_evento_fichaje', 'empresa_id')
    # ### end Alembic commands ###
