"""Modelo tipos de evento de fichaje asociado a la empresa

Revision ID: 7f2ca16c0841
Revises: cf553310ffe5
Create Date: 2026-08-14 12:00:54.135485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2ca16c0841'
down_revision: Union[str, Sequence[str], None] = 'cf553310ffe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipos_evento_fichaje', sa.Column('empresa_id', sa.Uuid(), nullable=True, comment='Nulo si es un tipo de evento global del sistema.'))
    op.create_foreign_key(None, 'tipos_evento_fichaje', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tipos_evento_fichaje', type_='foreignkey')
    op.drop_column('tipos_evento_fichaje', 'empresa_id')
    # ### end Alembic commands ###
