"""Cambio de tipo del id del tipo de evento de fichaje en fichajes a UUID

Revision ID: 8286b3c1ab45
Revises: 7f2ca16c0841
Create Date: 2026-08-14 20:20:01.817055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8286b3c1ab45'
down_revision: Union[str, Sequence[str], None] = '7f2ca16c0841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fichajes', 'tipo_evento_id',
               existing_type=sa.SMALLINT(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fichajes', 'tipo_evento_id',
               existing_type=sa.Uuid(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
