"""Cambio en los types y arreglo de error tabla duplicada de roles_permisos

Revision ID: 85e148bb9f29
Revises: 76060f7bb5af
Create Date: 2026-07-21 11:50:08.049442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85e148bb9f29'
down_revision: Union[str, Sequence[str], None] = '76060f7bb5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. ELIMINAMOS EL OBJETO PREVENTIVAMENTE TRATÁNDOLO COMO VISTA Y COMO TABLA
    op.execute('DROP VIEW IF EXISTS v_fichajes_vigentes CASCADE;')
    op.execute('DROP TABLE IF EXISTS v_fichajes_vigentes CASCADE;')

    # 2. CONTINÚA LA CREACIÓN NORMAL CALCULADA POR EL GENERADOR
    op.create_table('v_fichajes_vigentes',
    sa.Column('id', sa.Uuid(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('trabajador_id', sa.Uuid(), nullable=True),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=True),
    sa.Column('tipo_evento_id', sa.SmallInteger(), nullable=True),
    sa.Column('motivo_pausa_id', sa.SmallInteger(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_hora_dispositivo', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metodo_fichaje', postgresql.ENUM('App_móvil', 'Terminal_rfid', 'Terminal_pin', 'Lector_qr', 'Web', 'Geolocalización', 'Manual', name='metodo_fichaje_enum', create_type=False), nullable=True),
    sa.Column('dispositivo_id', sa.Uuid(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('origen', postgresql.ENUM('Trabajador', 'Corrección_rrhh', 'Sistema', name='origen_fichaje_enum', create_type=False), nullable=True),
    sa.Column('estado', postgresql.ENUM('Válido', 'Pendiente_revisión', name='estado_fichaje_enum', create_type=False), nullable=True),
    sa.Column('fichaje_sustituido_id', sa.Uuid(), nullable=True),
    sa.Column('hash_integridad', sa.String(length=64), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    comment='Fichajes con effecto legal actual: excluye los anulados (vía correcciones_fichaje aprobadas) y los ya sustituidos por una fila más reciente.'
    )
    
    op.alter_column('asignaciones_turno', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('ausencias', 'tipo_ausencia',
               existing_type=postgresql.ENUM('Vacaciones', 'Baja_temporal', 'Maternidad_paternidad', 'Permiso_retribuido', 'Ausencia_injustificada', name='tipo_ausencia_enum'),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('ausencias', 'estado',
               existing_type=postgresql.ENUM('Pendiente', 'Aprobada', 'Rechazada', name='estado_ausencia_enum'),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'Pendiente'::estado_ausencia_enum"))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ausencias', 'estado',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('Pendiente', 'Aprobada', 'Rechazada', name='estado_ausencia_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'Pendiente'::estado_ausencia_enum"))
    op.alter_column('ausencias', 'tipo_ausencia',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('Vacaciones', 'Baja_temporal', 'Maternidad_paternidad', 'Permiso_retribuido', 'Ausencia_injustificada', name='tipo_ausencia_enum'),
               existing_nullable=False)
    op.alter_column('asignaciones_turno', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_table('v_fichajes_vigentes')
    # ### end Alembic commands ###
