"""Actualización propiedades empresa_id y trabajador_id en usuarios ahora opcionales

Revision ID: 9a3f67a97dc6
Revises: 7c3d51af8879
Create Date: 2026-09-09 16:52:22.935195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3f67a97dc6'
down_revision: Union[str, Sequence[str], None] = '7c3d51af8879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='NULL para usuarios de la gestoría, administradores de empresa globales o auditores ITSS.',
               existing_comment='NULL para usuarios de la gestoría con acceso potencial a varias empresas (ámbito real definido en usuarios_roles).')
    op.alter_column('usuarios', 'trabajador_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'trabajador_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('usuarios', 'empresa_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='NULL para usuarios de la gestoría con acceso potencial a varias empresas (ámbito real definido en usuarios_roles).',
               existing_comment='NULL para usuarios de la gestoría, administradores de empresa globales o auditores ITSS.')
    # ### end Alembic commands ###
