"""Añadido modelo de licencias

Revision ID: 9e53143a9d0c
Revises: 68b56a04774d
Create Date: 2026-09-09 19:14:37.188034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e53143a9d0c'
down_revision: Union[str, Sequence[str], None] = '68b56a04774d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencias',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=50), server_default=sa.text("upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))"), nullable=False),
    sa.Column('usada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fecha_expiracion', sa.Date(), nullable=True),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='licencias_empresa_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='licencias_pkey'),
    sa.UniqueConstraint('codigo', name='licencias_codigo_key'),
    comment='Códigos de licencia de activación para el registro de nuevas empresas.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licencias')
    # ### end Alembic commands ###
