"""Actualización restricción dni de trabajadores para que tengan 8 dígitos y 1 letra

Revision ID: ae4b5f8be9dd
Revises: 33a3ff12e090
Create Date: 2026-09-03 18:24:52.612251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae4b5f8be9dd'
down_revision: Union[str, Sequence[str], None] = '33a3ff12e090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
