"""Nueva propiedad es_gestoria en empresa

Revision ID: bafe89b31672
Revises: 4d5bdf6e6df7
Create Date: 2026-09-10 17:07:49.136890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafe89b31672'
down_revision: Union[str, Sequence[str], None] = '4d5bdf6e6df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('es_gestoria', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_unique_constraint('licencias_empresa_id_key', 'licencias', ['empresa_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('licencias_empresa_id_key', 'licencias', type_='unique')
    op.drop_column('empresas', 'es_gestoria')
    # ### end Alembic commands ###
