"""Nueva propiedad para firma digital en fichajes

Revision ID: ca143b96b9bf
Revises: 20e5aecfa982
Create Date: 2026-09-02 11:04:48.618794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca143b96b9bf'
down_revision: Union[str, Sequence[str], None] = '20e5aecfa982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fichajes', sa.Column('firma_digital', sa.Text(), nullable=True, comment='Firma digitalizada en Base64 o URL del archivo.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fichajes', 'firma_digital')
    # ### end Alembic commands ###
