"""Actualización del código del main para producción

Revision ID: ca7dbf0bbe7d
Revises: 50842cc74af8
Create Date: 2026-07-21 12:47:03.137354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7dbf0bbe7d'
down_revision: Union[str, Sequence[str], None] = '50842cc74af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
