"""Mejora de seguridad: credenciales y aislamiento, manejo general, el Rate Limiting con SlowAPI en las rutas críticas, el CORS configurado en el main, las cabeceras y la validación de datos con pydantic

Revision ID: d3231b53004b
Revises: ca7dbf0bbe7d
Create Date: 2026-07-22 13:13:08.380931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3231b53004b'
down_revision: Union[str, Sequence[str], None] = 'ca7dbf0bbe7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
