"""Supresión de barrera de seguridad por permisos a ciertas rutas donde era innecesario y problemático

Revision ID: e4cb0249b3a4
Revises: d3231b53004b
Create Date: 2026-07-28 18:53:30.094474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cb0249b3a4'
down_revision: Union[str, Sequence[str], None] = 'd3231b53004b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
