"""base_de_datos_maestra

Revision ID: 76060f7bb5af
Revises: 
Create Date: 2026-06-19 12:04:38.241389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76060f7bb5af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('cif', sa.String(length=20), nullable=False),
    sa.Column('zona_horaria', sa.String(length=50), server_default=sa.text("'Europe/Madrid'::character varying"), nullable=False),
    sa.Column('configuracion', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('fecha_alta', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=True),
    sa.Column('codigo_cnae', sa.String(length=10), nullable=True),
    sa.Column('convenio_colectivo', sa.String(length=255), nullable=True),
    sa.Column('direccion_fiscal', sa.Text(), nullable=True),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='empresas_pkey'),
    sa.UniqueConstraint('cif', name='empresas_cif_key'),
    comment='Empresas cliente de la gestoría. Raíz de aislamiento multiempresa (tenant).'
    )
    op.create_table('permisos',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='permisos_pkey'),
    sa.UniqueConstraint('codigo', name='permisos_codigo_key')
    )
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('nombre', name='roles_nombre_key')
    )
    op.create_table('tipos_evento_fichaje',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('computa_como_trabajo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tipos_evento_fichaje_pkey'),
    sa.UniqueConstraint('codigo', name='tipos_evento_fichaje_codigo_key'),
    comment='Catálogo global: ENTRADA, SALIDA, INICIO_PAUSA, FIN_PAUSA, etc.'
    )
    op.create_table('centros_trabajo',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('zona_horaria', sa.String(length=50), server_default=sa.text("'Europe/Madrid'::character varying"), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('codigo_ccc', sa.String(length=20), nullable=True, comment='Código de Cuenta de Cotización a la Seguridad Social del centro, si aplica.'),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='centros_trabajo_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='centros_trabajo_pkey')
    )
    op.create_table('motivos_pausa',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('computa_como_trabajo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=True, comment='NULL = motivo del catálogo global (ej. comida, descanso legal); con valor = motivo propio de una empresa.'),
    sa.Column('duracion_max_minutos', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='motivos_pausa_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='motivos_pausa_pkey')
    )
    op.create_table('politicas_retencion',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('anios_conservacion', sa.SmallInteger(), server_default=sa.text('4'), nullable=False),
    sa.Column('accion_tras_periodo', sa.Enum('archivar', 'anonimizar', 'eliminar', name='accion_retencion_enum'), server_default=sa.text("'archivar'::accion_retencion_enum"), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('anios_conservacion >= 4', name='politicas_retencion_anios_conservacion_check'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='politicas_retencion_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='politicas_retencion_pkey'),
    sa.UniqueConstraint('empresa_id', name='politicas_retencion_empresa_id_key'),
    comment='Política de conservación legal (mínimo 4 años, art. 34.9 ET). empresa_id NULL = política global por defecto aplicada a empresas sin configuración propia.'
    )
    op.create_table('roles_permisos',
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('permiso_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], name='roles_permisos_permiso_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='roles_permisos_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permiso_id', name='roles_permisos_pkey')
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nif_nie', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fecha_alta_empresa', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('numero_seguridad_social', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_baja_empresa', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='trabajadores_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='trabajadores_pkey'),
    sa.UniqueConstraint('empresa_id', 'nif_nie', name='trabajadores_empresa_id_nif_nie_key'),
    comment='Trabajadores de cada empresa cliente. El derecho de supresión (art. 17 RGPD) no aplica mientras existan fichajes en periodo de conservación legal (excepción art. 17.3.b RGPD); en su lugar se usa activo/fecha_baja_empresa.'
    )
    op.create_table('turnos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('duracion_pausa_minutos', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('dias_semana', sa.ARRAY(sa.SmallInteger()), nullable=False, comment='Días de la semana en que aplica el turno: 1=lunes ... 7=domingo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dias_semana <@ ARRAY[1::smallint, 2::smallint, 3::smallint, 4::smallint, 5::smallint, 6::smallint, 7::smallint]', name='dias_semana_validos'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='turnos_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='turnos_pkey')
    )
    op.create_table('asignaciones_turno',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('turno_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='asignaciones_turno_check'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='asignaciones_turno_trabajador_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], name='asignaciones_turno_turno_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='asignaciones_turno_pkey')
    )
    op.create_table('calendarios_laborales',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centros_trabajo.id'], name='calendarios_laborales_centro_trabajo_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='calendarios_laborales_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='calendarios_laborales_pkey')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centros_trabajo.id'], name='departamentos_centro_trabajo_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='departamentos_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='departamentos_pkey')
    )
    op.create_table('dispositivos_fichaje',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_dispositivo', sa.Enum('app_movil', 'terminal_rfid', 'terminal_pin', 'lector_qr', 'web', 'geolocalizacion', 'manual', name='metodo_fichaje_enum'), nullable=False),
    sa.Column('identificador', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fecha_alta', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centros_trabajo.id'], name='dispositivos_fichaje_centro_trabajo_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='dispositivos_fichaje_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='dispositivos_fichaje_pkey'),
    sa.UniqueConstraint('empresa_id', 'identificador', name='dispositivos_fichaje_empresa_id_identificador_key'),
    comment='Terminales/medios de fichaje permitidos. No incluye biometría como método (prohibida en el borrador del nuevo RD salvo excepción legal).'
    )
    op.create_table('resumenes_jornada',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('minutos_trabajados', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('minutos_pausa', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('minutos_extra', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tiene_incidencia', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cerrado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hora_entrada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='resumenes_jornada_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='resumenes_jornada_trabajador_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='resumenes_jornada_pkey'),
    sa.UniqueConstraint('trabajador_id', 'fecha', name='resumenes_jornada_trabajador_id_fecha_key'),
    comment='Tabla de agregados diarios, recalculada por la aplicación (o un job) a partir de v_fichajes_vigentes. No sustituye a fichajes como prueba legal; es una capa de consulta rápida para nómina y cuadros de mando.'
    )
    op.create_index('idx_resumenes_empresa_fecha', 'resumenes_jornada', ['empresa_id', 'fecha'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('admin_gestoria', 'admin_empresa', 'rrhh', 'representante_legal', 'trabajador', 'auditor_itss', name='tipo_usuario_enum'), nullable=False),
    sa.Column('mfa_habilitado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=True, comment='NULL para usuarios de la gestoría con acceso potencial a varias empresas (ámbito real definido en usuarios_roles).'),
    sa.Column('trabajador_id', sa.Uuid(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='usuarios_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='usuarios_trabajador_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='usuarios_email_key'),
    sa.UniqueConstraint('trabajador_id', name='usuarios_trabajador_id_key')
    )
    op.create_table('auditoria_accesos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('accion', sa.Enum('consulta', 'exportacion', 'descarga', 'modificacion', 'acceso_denegado', name='accion_auditoria_enum'), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('trabajador_id', sa.Uuid(), nullable=True),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='auditoria_accesos_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='auditoria_accesos_trabajador_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='auditoria_accesos_usuario_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='auditoria_accesos_pkey'),
    comment='Registra cada consulta, exportación o descarga de fichajes: quién, de qué trabajador y cuándo. Sirve de prueba de que el sistema permite el acceso exigido por ley a trabajador, representantes legales e ITSS, y de detección de accesos indebidos.'
    )
    op.create_index('idx_auditoria_empresa_fecha', 'auditoria_accesos', ['empresa_id', 'fecha_hora'], unique=False)
    op.create_index('idx_auditoria_trabajador', 'auditoria_accesos', ['trabajador_id'], unique=False, postgresql_where='(trabajador_id IS NOT NULL)')
    op.create_table('ausencias',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_ausencia', sa.Enum('vacaciones', 'baja_temporal', 'maternidad_paternidad', 'permiso_retribuido', 'ausencia_injustificada', name='tipo_ausencia_enum'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estado_ausencia_enum'), server_default=sa.text("'pendiente'::estado_ausencia_enum"), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False, comment='Explicación o causa legal de la ausencia.'),
    sa.Column('justificante_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('validado_por_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observaciones_admin', sa.Text(), nullable=True, comment='Notas añadidas por el validador al aprobar/rechazar.'),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='ausencias_fechas_check'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='ausencias_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='ausencias_trabajador_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validado_por_usuario_id'], ['usuarios.id'], name='ausencias_validado_por_usuario_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='ausencias_pkey'),
    comment='Registro centralizado de ausencias, bajas y vacaciones. Requiere validación de RRHH.'
    )
    op.create_table('contratos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_contrato', sa.Enum('indefinido', 'temporal', 'formacion', 'practicas', 'fijo_discontinuo', 'otro', name='tipo_contrato_enum'), nullable=False),
    sa.Column('tipo_jornada', sa.Enum('completa', 'parcial', name='tipo_jornada_enum'), nullable=False),
    sa.Column('horas_semana', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('departamento_id', sa.Uuid(), nullable=True),
    sa.Column('puesto_trabajo', sa.String(length=150), nullable=True),
    sa.Column('categoria_profesional', sa.String(length=150), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='contratos_check'),
    sa.CheckConstraint('horas_semana > 0::numeric', name='contratos_horas_semana_check'),
    sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centros_trabajo.id'], name='contratos_centro_trabajo_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], name='contratos_departamento_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='contratos_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='contratos_trabajador_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='contratos_pkey')
    )
    op.create_table('festivos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('calendario_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=30), server_default=sa.text("'nacional'::character varying"), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['calendario_id'], ['calendarios_laborales.id'], name='festivos_calendario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='festivos_pkey'),
    sa.UniqueConstraint('calendario_id', 'fecha', name='festivos_calendario_id_fecha_key')
    )
    op.create_table('fichajes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_evento_id', sa.SmallInteger(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False, comment='Instante oficial del fichaje (referencia legal).'),
    sa.Column('metodo_fichaje', sa.Enum('app_movil', 'terminal_rfid', 'terminal_pin', 'lector_qr', 'web', 'geolocalizacion', 'manual', name='metodo_fichaje_enum'), nullable=False),
    sa.Column('origen', sa.Enum('trabajador', 'correccion_rrhh', 'sistema', name='origen_fichaje_enum'), server_default=sa.text("'trabajador'::origen_fichaje_enum"), nullable=False),
    sa.Column('estado', sa.Enum('valido', 'pendiente_revision', name='estado_fichaje_enum'), server_default=sa.text("'valido'::estado_fichaje_enum"), nullable=False),
    sa.Column('hash_integridad', sa.String(length=64), nullable=False, comment='SHA-256 calculado automáticamente sobre los campos clave del registro (ver trigger calcular_hash_fichaje), para evidenciar manipulación.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Momento real de inserción en el sistema (no editable); es la prueba temporal frente a fecha_hora, que puede haberse fijado manualmente en una corrección.'),
    sa.Column('motivo_pausa_id', sa.SmallInteger(), nullable=True),
    sa.Column('fecha_hora_dispositivo', sa.DateTime(timezone=True), nullable=True, comment='Hora reportada por el dispositivo/app del trabajador; permite detectar desincronización o manipulación del reloj local.'),
    sa.Column('dispositivo_id', sa.Uuid(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ip_address', sa.INTEGER(), nullable=True),
    sa.Column('fichaje_sustituido_id', sa.Uuid(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.CheckConstraint("latitud >= '-90'::integer::numeric AND latitud <= 90::numeric", name='fichajes_latitud_check'),
    sa.CheckConstraint("longitud >= '-180'::integer::numeric AND longitud <= 180::numeric", name='fichajes_longitud_check'),
    sa.ForeignKeyConstraint(['centro_trabajo_id'], ['centros_trabajo.id'], name='fichajes_centro_trabajo_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos_fichaje.id'], name='fichajes_dispositivo_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='fichajes_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fichaje_sustituido_id'], ['fichajes.id'], name='fichajes_fichaje_sustituido_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['motivo_pausa_id'], ['motivos_pausa.id'], name='fichajes_motivo_pausa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tipo_evento_id'], ['tipos_evento_fichaje.id'], name='fichajes_tipo_evento_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='fichajes_trabajador_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='fichajes_pkey'),
    comment='Registro de jornada. Tabla INMUTABLE (append-only): ver triggers de bloqueo de UPDATE/DELETE más abajo. Cualquier corrección se gestiona en correcciones_fichaje, opcionalmente insertando una nueva fila que referencia fichaje_sustituido_id.'
    )
    op.create_index('idx_fichajes_centro_fecha', 'fichajes', ['centro_trabajo_id', 'fecha_hora'], unique=False)
    op.create_index('idx_fichajes_empresa_fecha', 'fichajes', ['empresa_id', 'fecha_hora'], unique=False)
    op.create_index('idx_fichajes_sustituido', 'fichajes', ['fichaje_sustituido_id'], unique=False, postgresql_where='(fichaje_sustituido_id IS NOT NULL)')
    op.create_index('idx_fichajes_trabajador_fecha', 'fichajes', ['trabajador_id', 'fecha_hora'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=True, comment='Ámbito del rol. NULL = aplica a todas las empresas que gestiona el usuario (típico de personal de gestoría).'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='usuarios_roles_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='usuarios_roles_role_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='usuarios_roles_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='usuarios_roles_pkey'),
    sa.UniqueConstraint('usuario_id', 'role_id', 'empresa_id', name='usuarios_roles_usuario_id_role_id_empresa_id_key')
    )
    op.create_table('correcciones_fichaje',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_correccion', sa.Enum('alta_manual', 'modificacion', 'anulacion', name='tipo_correccion_enum'), nullable=False),
    sa.Column('valor_nuevo', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('solicitado_por_usuario_id', sa.Uuid(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estado_correccion_enum'), server_default=sa.text("'pendiente'::estado_correccion_enum"), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fichaje_afectado_id', sa.Uuid(), nullable=True),
    sa.Column('valor_anterior', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aprobado_por_usuario_id', sa.Uuid(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por_usuario_id'], ['usuarios.id'], name='correcciones_fichaje_aprobado_por_usuario_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='correcciones_fichaje_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fichaje_afectado_id'], ['fichajes.id'], name='correcciones_fichaje_fichaje_afectado_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitado_por_usuario_id'], ['usuarios.id'], name='correcciones_fichaje_solicitado_por_usuario_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='correcciones_fichaje_trabajador_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='correcciones_fichaje_pkey'),
    comment='Flujo auditable de altas manuales, modificaciones y anulaciones de fichajes. Esta tabla SÍ es mutable (estado pasa de pendiente a aprobada/rechazada), a diferencia de fichajes.'
    )
    op.create_index('idx_correcciones_empresa_estado', 'correcciones_fichaje', ['empresa_id', 'estado'], unique=False)
    op.create_index('idx_correcciones_fichaje_afectado', 'correcciones_fichaje', ['fichaje_afectado_id'], unique=False)
    op.execute("""
        CREATE OR REPLACE VIEW v_fichajes_vigentes AS
        SELECT f.id, f.empresa_id, f.trabajador_id, f.centro_trabajo_id, 
               f.tipo_evento_id, f.motivo_pausa_id, f.fecha_hora, f.fecha_hora_dispositivo,
               f.metodo_fichaje, f.dispositivo_id, f.latitud, f.longitud, f.ip_address,
               f.origen, f.estado, f.fichaje_sustituido_id, f.hash_integridad, 
               f.observaciones, f.created_at
        FROM fichajes f
        -- Aquí puedes añadir tu lógica de filtrado real, por ejemplo:
        -- WHERE f.estado = 'valido' AND f.fichaje_sustituido_id IS NULL;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_correcciones_fichaje_afectado', table_name='correcciones_fichaje')
    op.drop_index('idx_correcciones_empresa_estado', table_name='correcciones_fichaje')
    op.drop_table('correcciones_fichaje')
    op.drop_table('usuarios_roles')
    op.drop_index('idx_fichajes_trabajador_fecha', table_name='fichajes')
    op.drop_index('idx_fichajes_sustituido', table_name='fichajes', postgresql_where='(fichaje_sustituido_id IS NOT NULL)')
    op.drop_index('idx_fichajes_empresa_fecha', table_name='fichajes')
    op.drop_index('idx_fichajes_centro_fecha', table_name='fichajes')
    op.drop_table('fichajes')
    op.drop_table('festivos')
    op.drop_table('contratos')
    op.drop_table('ausencias')
    op.drop_index('idx_auditoria_trabajador', table_name='auditoria_accesos', postgresql_where='(trabajador_id IS NOT NULL)')
    op.drop_index('idx_auditoria_empresa_fecha', table_name='auditoria_accesos')
    op.drop_table('auditoria_accesos')
    op.drop_table('usuarios')
    op.drop_index('idx_resumenes_empresa_fecha', table_name='resumenes_jornada')
    op.drop_table('resumenes_jornada')
    op.drop_table('dispositivos_fichaje')
    op.drop_table('departamentos')
    op.drop_table('calendarios_laborales')
    op.drop_table('asignaciones_turno')
    op.drop_table('turnos')
    op.drop_table('trabajadores')
    op.drop_table('roles_permisos')
    op.drop_table('politicas_retencion')
    op.drop_table('motivos_pausa')
    op.drop_table('centros_trabajo')
    op.drop_table('tipos_evento_fichaje')
    op.drop_table('roles')
    op.drop_table('permisos')
    op.drop_table('empresas')
    op.execute("DROP VIEW IF EXISTS v_fichajes_vigentes;")
    # ### end Alembic commands ###
