/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authentication)'}/recuperar-password` | `/recuperar-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authentication)'}/registro` | `/registro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/empresas` | `/empresas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/fichajes` | `/fichajes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/horarios` | `/horarios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/incidencias` | `/incidencias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/plantilla` | `/plantilla`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/resolver-incidencias` | `/resolver-incidencias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/vacaciones` | `/vacaciones`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authentication)'}/recuperar-password` | `/recuperar-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(authentication)'}/registro` | `/registro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/empresas` | `/empresas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/fichajes` | `/fichajes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/horarios` | `/horarios`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/incidencias` | `/incidencias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/plantilla` | `/plantilla`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/resolver-incidencias` | `/resolver-incidencias`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(protected)'}/vacaciones` | `/vacaciones`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(authentication)'}/recuperar-password${`?${string}` | `#${string}` | ''}` | `/recuperar-password${`?${string}` | `#${string}` | ''}` | `${'/(authentication)'}/registro${`?${string}` | `#${string}` | ''}` | `/registro${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/empresas${`?${string}` | `#${string}` | ''}` | `/empresas${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/fichajes${`?${string}` | `#${string}` | ''}` | `/fichajes${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/horarios${`?${string}` | `#${string}` | ''}` | `/horarios${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/incidencias${`?${string}` | `#${string}` | ''}` | `/incidencias${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/plantilla${`?${string}` | `#${string}` | ''}` | `/plantilla${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/resolver-incidencias${`?${string}` | `#${string}` | ''}` | `/resolver-incidencias${`?${string}` | `#${string}` | ''}` | `${'/(protected)'}/vacaciones${`?${string}` | `#${string}` | ''}` | `/vacaciones${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authentication)'}/recuperar-password` | `/recuperar-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(authentication)'}/registro` | `/registro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/empresas` | `/empresas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/fichajes` | `/fichajes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/horarios` | `/horarios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/incidencias` | `/incidencias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/plantilla` | `/plantilla`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/resolver-incidencias` | `/resolver-incidencias`; params?: Router.UnknownInputParams; } | { pathname: `${'/(protected)'}/vacaciones` | `/vacaciones`; params?: Router.UnknownInputParams; };
    }
  }
}
