"""agregar cuenta_cotizacion

Revision ID: 1493858c771b
Revises: 
Create Date: 2026-04-21 19:40:53.871979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1493858c771b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('cif', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.String(), nullable=True),
    sa.Column('poblacion', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cif'), 'empresas', ['cif'], unique=True)
    op.create_index(op.f('ix_empresas_codigo_postal'), 'empresas', ['codigo_postal'], unique=False)
    op.create_index(op.f('ix_empresas_direccion'), 'empresas', ['direccion'], unique=False)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nombre'), 'empresas', ['nombre'], unique=False)
    op.create_index(op.f('ix_empresas_poblacion'), 'empresas', ['poblacion'], unique=False)
    op.create_index(op.f('ix_empresas_provincia'), 'empresas', ['provincia'], unique=False)
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellidos', sa.String(), nullable=True),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.String(), nullable=True),
    sa.Column('poblacion', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('cuenta_cotizacion', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trabajadores_apellidos'), 'trabajadores', ['apellidos'], unique=False)
    op.create_index(op.f('ix_trabajadores_codigo_postal'), 'trabajadores', ['codigo_postal'], unique=False)
    op.create_index(op.f('ix_trabajadores_cuenta_cotizacion'), 'trabajadores', ['cuenta_cotizacion'], unique=False)
    op.create_index(op.f('ix_trabajadores_direccion'), 'trabajadores', ['direccion'], unique=False)
    op.create_index(op.f('ix_trabajadores_dni'), 'trabajadores', ['dni'], unique=True)
    op.create_index(op.f('ix_trabajadores_email'), 'trabajadores', ['email'], unique=True)
    op.create_index(op.f('ix_trabajadores_id'), 'trabajadores', ['id'], unique=False)
    op.create_index(op.f('ix_trabajadores_nombre'), 'trabajadores', ['nombre'], unique=False)
    op.create_index(op.f('ix_trabajadores_password'), 'trabajadores', ['password'], unique=False)
    op.create_index(op.f('ix_trabajadores_poblacion'), 'trabajadores', ['poblacion'], unique=False)
    op.create_index(op.f('ix_trabajadores_provincia'), 'trabajadores', ['provincia'], unique=False)
    op.create_table('fichajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idTrabajador', sa.Integer(), nullable=False),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['idTrabajador'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id', 'idTrabajador', 'idEmpresa')
    )
    op.create_index(op.f('ix_fichajes_fecha_hora'), 'fichajes', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_fichajes_id'), 'fichajes', ['id'], unique=False)
    op.create_index(op.f('ix_fichajes_idEmpresa'), 'fichajes', ['idEmpresa'], unique=False)
    op.create_index(op.f('ix_fichajes_idTrabajador'), 'fichajes', ['idTrabajador'], unique=False)
    op.create_index(op.f('ix_fichajes_tipo'), 'fichajes', ['tipo'], unique=False)
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idTrabajador', sa.Integer(), nullable=False),
    sa.Column('idEmpresa', sa.Integer(), nullable=False),
    sa.Column('tipoJornada', sa.String(), nullable=True),
    sa.Column('dias', sa.Integer(), nullable=True),
    sa.Column('dias_semana', sa.String(), nullable=True),
    sa.Column('hora_entrada', sa.DateTime(), nullable=True),
    sa.Column('hora_salida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['idTrabajador'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id', 'idTrabajador', 'idEmpresa')
    )
    op.create_index(op.f('ix_horarios_dias'), 'horarios', ['dias'], unique=False)
    op.create_index(op.f('ix_horarios_dias_semana'), 'horarios', ['dias_semana'], unique=False)
    op.create_index(op.f('ix_horarios_hora_entrada'), 'horarios', ['hora_entrada'], unique=False)
    op.create_index(op.f('ix_horarios_hora_salida'), 'horarios', ['hora_salida'], unique=False)
    op.create_index(op.f('ix_horarios_id'), 'horarios', ['id'], unique=False)
    op.create_index(op.f('ix_horarios_idEmpresa'), 'horarios', ['idEmpresa'], unique=False)
    op.create_index(op.f('ix_horarios_idTrabajador'), 'horarios', ['idTrabajador'], unique=False)
    op.create_index(op.f('ix_horarios_tipoJornada'), 'horarios', ['tipoJornada'], unique=False)
    op.create_table('trabajador_empresa',
    sa.Column('trabajador_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trabajador_empresa')
    op.drop_index(op.f('ix_horarios_tipoJornada'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_idTrabajador'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_idEmpresa'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_id'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_hora_salida'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_hora_entrada'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_dias_semana'), table_name='horarios')
    op.drop_index(op.f('ix_horarios_dias'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_fichajes_tipo'), table_name='fichajes')
    op.drop_index(op.f('ix_fichajes_idTrabajador'), table_name='fichajes')
    op.drop_index(op.f('ix_fichajes_idEmpresa'), table_name='fichajes')
    op.drop_index(op.f('ix_fichajes_id'), table_name='fichajes')
    op.drop_index(op.f('ix_fichajes_fecha_hora'), table_name='fichajes')
    op.drop_table('fichajes')
    op.drop_index(op.f('ix_trabajadores_provincia'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_poblacion'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_password'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_nombre'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_id'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_email'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_dni'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_direccion'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_cuenta_cotizacion'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_codigo_postal'), table_name='trabajadores')
    op.drop_index(op.f('ix_trabajadores_apellidos'), table_name='trabajadores')
    op.drop_table('trabajadores')
    op.drop_index(op.f('ix_empresas_provincia'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_poblacion'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_nombre'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_direccion'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_codigo_postal'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cif'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
