"""initial_db

Revision ID: f57ffa9d794e
Revises: 
Create Date: 2026-10-09 10:41:01.271305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f57ffa9d794e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la empresa.'),
    sa.Column('nombre_comercial', sa.String(length=50), nullable=False, comment='Nombre comercial de la empresa.'),
    sa.Column('razon_social', sa.String(length=50), nullable=False, comment='Razón social de la empresa.'),
    sa.Column('cif', sa.String(length=20), nullable=False, comment='CIF de la empresa.'),
    sa.Column('zona_horaria', sa.String(length=50), server_default=sa.text("'Europe/Madrid'::character varying"), nullable=False, comment='Zona horaria de la empresa.'),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si la empresa está activa.'),
    sa.Column('configuracion', sa.JSON(), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Configuración de la empresa.'),
    sa.Column('es_gestoria', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Indica si la empresa es una gestoría.'),
    sa.Column('codigo_cnae', sa.String(length=10), nullable=True, comment='Código CNAE de la empresa.'),
    sa.Column('convenio_colectivo', sa.String(length=50), nullable=True, comment='Convenio colectivo aplicable a la empresa.'),
    sa.Column('direccion_fiscal', sa.String(length=50), nullable=True, comment='Dirección fiscal de la empresa.'),
    sa.Column('fecha_baja', sa.Date(), nullable=True, comment='Fecha de baja de la empresa.'),
    sa.Column('logo_url', sa.Text(), nullable=True, comment='URL del logo de la empresa.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación de la empresa.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización de la empresa.'),
    sa.PrimaryKeyConstraint('id', name='empresas_pkey'),
    sa.UniqueConstraint('cif', name='empresas_cif_key'),
    comment='Empresas cliente de la gestoría. Raíz de aislamiento multiempresa (tenant).'
    )
    op.create_table('permisos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del permiso.'),
    sa.Column('tipo', sa.Enum('asignaciones_turno', 'auditoria_accesos', 'ausencias', 'calendarios_laborales', 'centros_trabajo', 'contratos_calendarios', 'contratos', 'correcciones_fichaje', 'departamentos', 'dispositivos_fichaje', 'empresas', 'festivos', 'fichajes', 'gestorias_empresas', 'licencias', 'motivos_pausa', 'permisos', 'politicas_retencion', 'resumenes_jornada', 'roles_permisos', 'roles', 'trabajadores', 'turnos', 'usuarios_empresas', 'usuarios', name='tipo_permiso_enum'), server_default=sa.text("'usuarios'::tipo_permiso_enum"), nullable=False, comment='Recurso o área funcional a la que aplica el permiso.'),
    sa.Column('accion', sa.Enum('consultar', 'crear', 'modificar', 'eliminar', 'aprobar', 'exportar', 'fichar', name='accion_permiso_enum'), server_default=sa.text("'consultar'::accion_permiso_enum"), nullable=False, comment='Operación autorizada sobre el recurso.'),
    sa.Column('descripcion', sa.String(length=255), nullable=True, comment='Descripción del permiso.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la licencia.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización de la licencia.'),
    sa.PrimaryKeyConstraint('id', name='permisos_pkey'),
    sa.UniqueConstraint('tipo', 'accion', name='permisos_tipo_accion_key'),
    comment='Permisos que pueden ser asignados a roles para controlar el acceso a funcionalidades del sistema.'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del usuario.'),
    sa.Column('nombre', sa.String(length=150), nullable=False, comment='Nombre completo del usuario.'),
    sa.Column('email', sa.String(length=30), nullable=False, comment='Dirección de correo electrónico del usuario.'),
    sa.Column('telefono', sa.String(length=30), nullable=True, comment='Número de teléfono del usuario.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hash de la contraseña del usuario.'),
    sa.Column('mfa_habilitado', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Indica si el usuario tiene habilitada la autenticación de dos factores.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el usuario está activo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del usuario.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización del usuario.'),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True, comment='Fecha del último acceso del usuario.'),
    sa.Column('codigo_recuperacion', sa.String(length=10), nullable=True, comment='Código de recuperación para restablecimiento de contraseña.'),
    sa.Column('codigo_expira_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de expiración del código de recuperación.'),
    sa.Column('email_pendiente_verificacion', sa.String(length=30), nullable=True, comment='Dirección de correo electrónico pendiente de verificación.'),
    sa.Column('token_cambio_email', sa.String(length=255), nullable=True, comment='Token para cambiar la dirección de correo electrónico.'),
    sa.Column('token_cambio_email_expira_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de expiracion del token para cambiar el correo electrónico.'),
    sa.Column('telefono_pendiente_verificacion', sa.String(length=30), nullable=True, comment='Número de teléfono pendiente de verificación.'),
    sa.Column('token_cambio_telefono', sa.String(length=255), nullable=True, comment='Token para cambiar el número de teléfono.'),
    sa.Column('token_cambio_telefono_expira_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha de expiración del token para cambiar el número de teléfono.'),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    sa.UniqueConstraint('token_cambio_email'),
    sa.UniqueConstraint('token_cambio_telefono'),
    comment='Usuarios de la aplicación; pueden ser trabajadores, administradores de empresa o usuarios de sistema.'
    )
    op.create_index('usuarios_email_activo_key', 'usuarios', ['email'], unique=True, postgresql_where=sa.text('activo IS TRUE'))
    op.create_index('usuarios_telefono_activo_key', 'usuarios', ['telefono'], unique=True, postgresql_where=sa.text('activo IS TRUE'))
    op.create_table('centros_trabajo',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del centro de trabajo.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el centro de trabajo.'),
    sa.Column('nombre', sa.String(length=50), nullable=False, comment='Nombre del centro de trabajo.'),
    sa.Column('zona_horaria', sa.String(length=50), server_default=sa.text("'Europe/Madrid'::character varying"), nullable=False, comment='Zona horaria del centro de trabajo.'),
    sa.Column('codigo_ccc', sa.String(length=20), nullable=True, comment='Código de Cuenta de Cotización a la Seguridad Social del centro, si aplica.'),
    sa.Column('direccion', sa.String(length=50), nullable=True, comment='Dirección del centro de trabajo.'),
    sa.Column('latitud', sa.Numeric(precision=10, scale=6), nullable=True, comment='Latitud de la ubicación del centro de trabajo.'),
    sa.Column('longitud', sa.Numeric(precision=10, scale=6), nullable=True, comment='Longitud de la ubicación del centro de trabajo.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el centro de trabajo está activo o inactivo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del registro.'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='centros_trabajo_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='centros_trabajo_pkey'),
    sa.UniqueConstraint('empresa_id', 'id', name='centros_trabajo_empresa_id_id_key'),
    comment='Centros de trabajo de la empresa. Se pueden definir varios centros de trabajo para una misma empresa, cada uno con su propio calendario laboral y ubicación.'
    )
    op.create_table('gestorias_empresas',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la relación gestoría-empresa cliente.'),
    sa.Column('empresa_gestora_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa gestora.'),
    sa.Column('empresa_cliente_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa cliente.'),
    sa.Column('usuario_creador_id', sa.Uuid(), nullable=True, comment='Identificador del usuario que creó la autorización.'),
    sa.Column('fecha_inicio', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='Fecha de inicio de la autorización.'),
    sa.Column('fecha_fin', sa.Date(), nullable=True, comment='Fecha de finalización de la autorización.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si la relacion entre la gestoría y la empresa cliente está activa o no.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la autorización.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización de la autorización.'),
    sa.CheckConstraint('empresa_gestora_id <> empresa_cliente_id', name='gestorias_empresas_empresas_distintas_check'),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='gestorias_empresas_fechas_check'),
    sa.ForeignKeyConstraint(['empresa_cliente_id'], ['empresas.id'], name='gestorias_empresas_empresa_cliente_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_gestora_id'], ['empresas.id'], name='gestorias_empresas_empresa_gestora_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], name='gestorias_empresas_usuario_creador_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='gestorias_empresas_pkey'),
    comment='Autorizaciones vigentes e históricas de gestorías sobre empresas cliente.'
    )
    op.create_index('gestorias_empresas_cliente_activo_idx', 'gestorias_empresas', ['empresa_cliente_id', 'activo'], unique=False)
    op.create_index('gestorias_empresas_gestoria_activo_idx', 'gestorias_empresas', ['empresa_gestora_id', 'activo'], unique=False)
    op.create_index('gestorias_empresas_vinculo_activo_key', 'gestorias_empresas', ['empresa_gestora_id', 'empresa_cliente_id'], unique=True, postgresql_where=sa.text('activo IS TRUE'))
    op.create_table('licencias',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la licencia.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Empresa que canjeó la licencia; NULL mientras el código no se haya utilizado.'),
    sa.Column('codigo', sa.String(length=12), server_default=sa.text("upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12))"), nullable=False, comment='Código único para canjear la licencia comercial.'),
    sa.Column('plan', sa.Enum('Básico', 'Pro', 'Enterprise', name='plan_licencia_enum'), server_default=sa.text("'Básico'::plan_licencia_enum"), nullable=False, comment='Nivel del plan contratado (Básico, Pro, Enterprise).'),
    sa.Column('ciclo', sa.Enum('Trial', 'Mensual', 'Anual', name='ciclo_facturacion_enum'), server_default=sa.text("'Trial'::ciclo_facturacion_enum"), nullable=False, comment='Ciclo de facturación (Trial, Mensual, Anual).'),
    sa.Column('estado', sa.Enum('Trialing', 'Activa', 'Vencida', 'Cancelada', name='estado_suscripcion_enum'), server_default=sa.text("'Trialing'::estado_suscripcion_enum"), nullable=False, comment='Estado actual de la suscripción.'),
    sa.Column('fecha_inicio', sa.Date(), server_default=sa.text('current_date'), nullable=False, comment='Inicio del periodo actual de vigencia.'),
    sa.Column('fecha_expiracion', sa.Date(), nullable=False, comment='Fecha exacta en que expira el periodo de prueba (Trial) o la suscripción pagada.'),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True, comment='ID de la suscripción en la pasarela de pagos (Stripe).'),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True, comment='ID del cliente en la pasarela de pagos.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la licencia.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización de la licencia.'),
    sa.Column('revocada_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha en que se revocó la licencia, si corresponde.'),
    sa.CheckConstraint('fecha_expiracion IS NULL OR fecha_inicio IS NULL OR fecha_expiracion >= fecha_inicio', name='licencias_rango_vigencia_check'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='licencias_empresa_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='licencias_pkey'),
    sa.UniqueConstraint('empresa_id', name='licencias_empresa_id_key'),
    sa.UniqueConstraint('stripe_subscription_id'),
    comment='Suscripciones y licencias SaaS de las empresas (Trial de 14 días, Básico, Pro, Enterprise con facturación mensual o anual).'
    )
    op.create_table('motivos_pausa',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del motivo de pausa.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=True, comment='NULL = motivo del catálogo global (ej. comida, descanso legal); con valor = motivo propio de una empresa.'),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment='Nombre del motivo de pausa.'),
    sa.Column('computa_como_trabajo', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Indica si el tiempo de pausa con este motivo se computa como tiempo trabajado o no.'),
    sa.Column('duracion_max_minutos', sa.SmallInteger(), nullable=True, comment='Duración máxima en minutos para este motivo de pausa.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la licencia.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización de la licencia.'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='motivos_pausa_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='motivos_pausa_pkey'),
    comment='Motivos de pausa que pueden ser utilizados en los fichajes de los trabajadores. Pueden ser motivos globales (empresa_id = NULL) o motivos propios de una empresa (empresa_id = valor).'
    )
    op.create_table('politicas_retencion',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la política de retención.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=True, comment='NULL = política global por defecto; con valor = política propia de una empresa.'),
    sa.Column('anios_conservacion', sa.SmallInteger(), server_default=sa.text('4'), nullable=False, comment='Número de años que se conservarán los datos antes de aplicar la acción de retención.'),
    sa.Column('accion_tras_periodo', sa.Enum('Archivar', 'Anonimizar', 'Eliminar', name='accion_retencion_enum'), server_default=sa.text("'Archivar'::accion_retencion_enum"), nullable=False, comment='Acción a realizar sobre los datos una vez transcurrido el periodo de conservación.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la licencia.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización de la licencia.'),
    sa.CheckConstraint('anios_conservacion >= 4', name='politicas_retencion_anios_conservacion_check'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='politicas_retencion_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='politicas_retencion_pkey'),
    comment='Política global de retención (empresa_id NULL) y overrides empresariales que nunca deben reducir el mínimo global.'
    )
    op.create_index('politicas_retencion_unica_global_key', 'politicas_retencion', [sa.literal_column('(1)')], unique=True, postgresql_where=sa.text('empresa_id IS NULL'))
    op.create_index('politicas_retencion_unica_por_empresa_key', 'politicas_retencion', ['empresa_id'], unique=True, postgresql_where=sa.text('empresa_id IS NOT NULL'))
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del rol.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=True, comment='NULL para rol de sistema; con empresa_id es un rol personalizado de esa empresa.'),
    sa.Column('nombre', sa.String(length=50), nullable=False, comment='Nombre del rol; único por empresa o global (empresa_id = NULL).'),
    sa.Column('tipo', sa.Enum('Superadministrador', 'Admin_gestoría', 'Admin_empresa', 'Rrhh', 'Representante_legal', 'Trabajador', 'Auditor_itss', 'Otro', name='tipo_rol_enum'), server_default=sa.text("'Otro'::tipo_rol_enum"), nullable=False, comment='Tipo de rol.'),
    sa.Column('descripcion', sa.String(length=255), nullable=True, comment='Descripción del rol.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del rol.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del rol.'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='roles_empresa_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    comment='Roles de acceso a la aplicación; pueden ser roles globales (empresa_id = NULL) o roles personalizados de empresa (empresa_id = valor).'
    )
    op.create_index('roles_empresa_nombre_key', 'roles', ['empresa_id', 'nombre'], unique=True, postgresql_where=sa.text('empresa_id IS NOT NULL'))
    op.create_index('roles_nombre_global_key', 'roles', ['nombre'], unique=True, postgresql_where=sa.text('empresa_id IS NULL'))
    op.create_table('turnos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del turno.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el turno; NULL para turno global.'),
    sa.Column('nombre', sa.String(length=150), nullable=False, comment='Nombre del turno.'),
    sa.Column('hora_inicio', sa.Time(), nullable=False, comment='Hora de inicio del turno.'),
    sa.Column('hora_fin', sa.Time(), nullable=False, comment='Hora de fin del turno.'),
    sa.Column('duracion_pausa_minutos', sa.SmallInteger(), server_default=sa.text('0'), nullable=False, comment='Duración de la pausa en minutos para este turno; se puede usar para calcular el tiempo efectivo de trabajo.'),
    sa.Column('dias_semana', sa.ARRAY(sa.SmallInteger()), server_default=sa.text("'{1,2,3,4,5}'"), nullable=False, comment='Días de la semana en que aplica el turno: 1=lunes ... 7=domingo.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el turno está activo; los turnos inactivos no se pueden asignar a trabajadores.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del turno.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización del turno.'),
    sa.CheckConstraint('dias_semana <@ ARRAY[1::smallint, 2::smallint, 3::smallint, 4::smallint, 5::smallint, 6::smallint, 7::smallint]', name='dias_semana_validos'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='turnos_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='turnos_pkey'),
    sa.UniqueConstraint('empresa_id', 'id', name='turnos_empresa_id_id_key'),
    comment='Turnos de trabajo que pueden ser asignados a los trabajadores; pueden ser turnos globales (empresa_id = NULL) o turnos propios de una empresa (empresa_id = valor).'
    )
    op.create_table('calendarios_laborales',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del calendario laboral.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el calendario.'),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=False, comment='Centro físico al que pertenece este calendario anual.'),
    sa.Column('anio', sa.SmallInteger(), nullable=False, comment='Año al que corresponde el calendario.'),
    sa.Column('nombre', sa.String(length=50), nullable=False, comment='Nombre del calendario laboral.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el calendario está activo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del registro.'),
    sa.ForeignKeyConstraint(['empresa_id', 'centro_trabajo_id'], ['centros_trabajo.empresa_id', 'centros_trabajo.id'], name='calendarios_laborales_empresa_centro_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='calendarios_laborales_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='calendarios_laborales_pkey'),
    sa.UniqueConstraint('empresa_id', 'centro_trabajo_id', 'anio', name='calendarios_laborales_empresa_centro_anio_key'),
    sa.UniqueConstraint('empresa_id', 'centro_trabajo_id', 'id', name='calendarios_laborales_empresa_centro_id_key'),
    sa.UniqueConstraint('empresa_id', 'id', name='calendarios_laborales_empresa_id_id_key'),
    comment='Calendarios laborales que definen los días laborables y festivos de la empresa o centro de trabajo.'
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del departamento.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el departamento.'),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=False, comment='Identificador del centro de trabajo al que pertenece el departamento.'),
    sa.Column('nombre', sa.String(length=255), nullable=False, comment='Nombre del departamento.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el departamento está activo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del departamento.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del departamento.'),
    sa.ForeignKeyConstraint(['empresa_id', 'centro_trabajo_id'], ['centros_trabajo.empresa_id', 'centros_trabajo.id'], name='departamentos_empresa_centro_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='departamentos_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='departamentos_pkey'),
    sa.UniqueConstraint('empresa_id', 'id', name='departamentos_empresa_id_id_key'),
    comment='Departamentos de la empresa o centro de trabajo. Se pueden usar para clasificar a los trabajadores y asignarles turnos, calendarios laborales, etc.'
    )
    op.create_table('dispositivos_fichaje',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del dispositivo de fichaje.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el dispositivo.'),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=False, comment='Identificador del centro de trabajo al que pertenece el dispositivo.'),
    sa.Column('tipo_dispositivo', sa.Enum('App_móvil', 'Terminal_rfid', 'Terminal_pin', 'Lector_qr', 'Web', 'Geolocalización', 'Manual', name='metodo_fichaje_enum'), server_default=sa.text("'Manual'::metodo_fichaje_enum"), nullable=False, comment='Tipo de dispositivo de fichaje.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el dispositivo de fichaje está activo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del dispositivo de fichaje.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del dispositivo de fichaje.'),
    sa.ForeignKeyConstraint(['empresa_id', 'centro_trabajo_id'], ['centros_trabajo.empresa_id', 'centros_trabajo.id'], name='dispositivos_fichaje_empresa_centro_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='dispositivos_fichaje_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='dispositivos_fichaje_pkey'),
    sa.UniqueConstraint('empresa_id', 'id', name='dispositivos_fichaje_empresa_id_id_key'),
    comment='Terminales/medios de fichaje permitidos. No incluye biometría como método (prohibida en el borrador del nuevo RD salvo excepción legal).'
    )
    op.create_table('roles_permisos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la relación rol-permiso.'),
    sa.Column('rol_id', sa.Uuid(), nullable=False, comment='Identificador del rol al que pertenece la relación rol-permiso.'),
    sa.Column('permiso_id', sa.Uuid(), nullable=False, comment='Identificador del permiso al que pertenece la relación rol-permiso.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación de la relación rol-permiso.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización de la relación rol-permiso.'),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], name='roles_permisos_permiso_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name='roles_permisos_rol_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='roles_permisos_pkey'),
    comment='Relación entre roles y permisos; un rol puede tener múltiples permisos y un permiso puede pertenecer a múltiples roles.'
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del trabajador.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el trabajador.'),
    sa.Column('rol_id', sa.Uuid(), nullable=True, comment='Identificador del rol de acceso del trabajador.'),
    sa.Column('dni_nif_nie', sa.String(length=9), nullable=False, comment='DNI, NIF o NIE del trabajador; único por empresa.'),
    sa.Column('nombre', sa.String(length=50), nullable=False, comment='Nombre del trabajador.'),
    sa.Column('apellidos', sa.String(length=100), nullable=False, comment='Apellidos del trabajador.'),
    sa.Column('numero_seguridad_social', sa.String(length=20), nullable=True, comment='Número de la Seguridad Social del trabajador; único por empresa si no es nulo.'),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True, comment='Fecha de nacimiento del trabajador.'),
    sa.Column('foto_url', sa.Text(), nullable=True, comment='URL de la foto del trabajador; se puede usar para identificación visual en fichajes.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el trabajador está activo; se usa para cumplir con el derecho de supresión (art. 17 RGPD) mientras existan fichajes en periodo de conservación legal.'),
    sa.Column('estado', sa.Enum('Inactivo', 'Activo', 'Trabajando', 'Descansando', 'Haciendo_horas_extra', 'De_vacaciones', 'De_baja', 'Ausente', name='estado_trabajador_enum'), server_default=sa.text("'Inactivo'::estado_trabajador_enum"), nullable=False, comment='Estado operativo actual del trabajador'),
    sa.Column('fecha_alta_empresa', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='Fecha de alta del trabajador en la empresa; se usa para cumplir con el derecho de supresión (art. 17 RGPD) mientras existan fichajes en periodo de conservación legal.'),
    sa.Column('fecha_baja_empresa', sa.Date(), nullable=True, comment='Fecha de baja del trabajador en la empresa; se usa para cumplir con el derecho de supresión (art. 17 RGPD) mientras existan fichajes en periodo de conservación legal.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del trabajador.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización del trabajador.'),
    sa.CheckConstraint("dni_nif_nie ~ '^[XYZ0-9][0-9]{7}[A-Za-z]$'", name='check_dni_nif_nie_formato_valido'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='trabajadores_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name='trabajadores_rol_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='trabajadores_pkey'),
    sa.UniqueConstraint('empresa_id', 'dni_nif_nie', name='trabajadores_empresa_id_dni_nif_nie_key'),
    sa.UniqueConstraint('empresa_id', 'id', name='trabajadores_empresa_id_id_key'),
    comment='Trabajadores de cada empresa cliente. El derecho de supresión (art. 17 RGPD) no aplica mientras existan fichajes en periodo de conservación legal (excepción art. 17.3.b RGPD); en su lugar se usa activo/fecha_baja_empresa.'
    )
    op.create_table('usuarios_empresas',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la relación usuario-empresa.'),
    sa.Column('usuario_id', sa.Uuid(), nullable=False, comment='Identificador del usuario.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa.'),
    sa.Column('rol_id', sa.Uuid(), nullable=False, comment='Único rol de acceso de este usuario en esta empresa.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si la relación es activa.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación de la relación.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización de la relación.'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='usuarios_empresas_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name='usuarios_empresas_rol_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='usuarios_empresas_usuario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='usuarios_empresas_pkey'),
    sa.UniqueConstraint('usuario_id', 'empresa_id', name='usuarios_empresas_usuario_id_empresa_id_key'),
    comment='Membresías y acceso de usuarios a empresas; los roles se asignan por separado.'
    )
    op.create_index('usuarios_empresas_empresa_activo_idx', 'usuarios_empresas', ['empresa_id', 'activo'], unique=False)
    op.create_table('auditoria_accesos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del registro de auditoría.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=True, comment='Identificador de la empresa a la que pertenece el registro.'),
    sa.Column('usuario_id', sa.Uuid(), nullable=True, comment='Identificador del usuario que realiza la acción.'),
    sa.Column('trabajador_id', sa.Uuid(), nullable=True, comment='Identificador del trabajador relacionado con la acción.'),
    sa.Column('accion', sa.Enum('Consulta', 'Creación', 'Modificación', 'Baja_lógica', 'Eliminación', 'Exportación', 'Importación', 'Descarga', 'Acceso_denegado', name='accion_auditoria_enum'), server_default=sa.text("'Consulta'::accion_auditoria_enum"), nullable=False, comment='Tipo de acción realizada.'),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora en que se realiza la acción.'),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detalles adicionales sobre la acción realizada.'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Dirección IP desde donde se realiza la acción.'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='auditoria_accesos_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], name='auditoria_accesos_trabajador_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='auditoria_accesos_usuario_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='auditoria_accesos_pkey'),
    comment='Registra cada consulta, exportación o descarga de fichajes: quién, de qué trabajador y cuándo. Sirve de prueba de que el sistema permite el acceso exigido por ley a trabajador, representantes legales e ITSS, y de detección de accesos indebidos.'
    )
    op.create_index('idx_auditoria_empresa_fecha', 'auditoria_accesos', ['empresa_id', 'fecha_hora'], unique=False)
    op.create_index('idx_auditoria_trabajador', 'auditoria_accesos', ['trabajador_id'], unique=False, postgresql_where='(trabajador_id IS NOT NULL)')
    op.create_index('idx_auditoria_usuario', 'auditoria_accesos', ['usuario_id'], unique=False, postgresql_where='(usuario_id IS NOT NULL)')
    op.create_table('ausencias',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la ausencia.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece la ausencia.'),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False, comment='Identificador del trabajador que tiene la ausencia.'),
    sa.Column('usuario_validador_id', sa.Uuid(), nullable=True, comment='Identificador del usuario que valida o resuelve la solicitud de ausencia.'),
    sa.Column('tipo_ausencia', sa.Enum('Vacaciones', 'Baja_temporal', 'Maternidad_paternidad', 'Permiso_retribuido', 'Asuntos_propios', 'Ausencia_injustificada', name='tipo_ausencia_enum'), server_default=sa.text("'Ausencia_injustificada'::tipo_ausencia_enum"), nullable=False, comment='Tipo de ausencia (vacaciones, baja médica, etc.).'),
    sa.Column('estado', sa.Enum('Pendiente', 'Aprobada', 'Rechazada', 'Cancelada', name='estado_ausencia_enum'), server_default=sa.text("'Pendiente'::estado_ausencia_enum"), nullable=False, comment='Estado de la ausencia.'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False, comment='Fecha de inicio de la ausencia.'),
    sa.Column('fecha_fin', sa.Date(), nullable=False, comment='Fecha de fin de la ausencia.'),
    sa.Column('motivo', sa.String(length=255), nullable=False, comment='Explicación o causa legal de la ausencia.'),
    sa.Column('justificante_url', sa.Text(), nullable=True, comment='URL o ruta del archivo PDF oficial del justificante de la ausencia.'),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True, comment='Fecha en que se resuelve la solicitud de ausencia.'),
    sa.Column('observaciones_admin', sa.String(length=255), nullable=True, comment='Notas añadidas por el validador al aprobar/rechazar.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del registro.'),
    sa.CheckConstraint('fecha_fin >= fecha_inicio', name='ausencias_fechas_check'),
    sa.ForeignKeyConstraint(['empresa_id', 'trabajador_id'], ['trabajadores.empresa_id', 'trabajadores.id'], name='ausencias_empresa_trabajador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='ausencias_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_validador_id'], ['usuarios.id'], name='ausencias_usuario_validador_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='ausencias_pkey'),
    comment='Registra las ausencias de los trabajadores, incluyendo vacaciones, bajas médicas y otros tipos de ausencia. Permite a la empresa gestionar y justificar las ausencias de los trabajadores, '
    )
    op.create_table('contratos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del contrato.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el contrato.'),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False, comment='Identificador del trabajador al que corresponde el contrato.'),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=False, comment='Identificador del centro de trabajo al que pertenece el contrato.'),
    sa.Column('departamento_id', sa.Uuid(), nullable=False, comment='Departamento al que pertenece el contrato.'),
    sa.Column('tipo_contrato', sa.Enum('Indefinido', 'Temporal', 'Formación', 'Prácticas', 'Fijo_discontinuo', 'Otro', name='tipo_contrato_enum'), server_default=sa.text("'Temporal'::tipo_contrato_enum"), nullable=False, comment='Tipo de contrato.'),
    sa.Column('tipo_jornada', sa.Enum('Completa', 'Parcial', name='tipo_jornada_enum'), server_default=sa.text("'Completa'::tipo_jornada_enum"), nullable=False, comment='Tipo de jornada.'),
    sa.Column('horas_semana', sa.Numeric(precision=5, scale=2), nullable=False, comment='Número de horas semanales del contrato.'),
    sa.Column('puesto_trabajo', sa.String(length=50), nullable=True, comment='Puesto de trabajo del contratado.'),
    sa.Column('categoria_profesional', sa.String(length=50), nullable=True, comment='Categoría profesional del contratado.'),
    sa.Column('pdf_url', sa.Text(), nullable=True, comment='URL o ruta del archivo PDF oficial del contrato.'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False, comment='Fecha de inicio del contrato.'),
    sa.Column('fecha_fin', sa.Date(), nullable=True, comment='Fecha de fin del contrato. Si es NULL, el contrato está activo hasta que se indique lo contrario.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el contrato está activo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del contrato.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del contrato.'),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='contratos_check'),
    sa.CheckConstraint('horas_semana > 0::numeric', name='contratos_horas_semana_check'),
    sa.ForeignKeyConstraint(['empresa_id', 'centro_trabajo_id'], ['centros_trabajo.empresa_id', 'centros_trabajo.id'], name='contratos_empresa_centro_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id', 'departamento_id'], ['departamentos.empresa_id', 'departamentos.id'], name='contratos_empresa_departamento_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id', 'trabajador_id'], ['trabajadores.empresa_id', 'trabajadores.id'], name='contratos_empresa_trabajador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='contratos_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='contratos_pkey'),
    sa.UniqueConstraint('empresa_id', 'centro_trabajo_id', 'id', name='contratos_empresa_centro_id_key'),
    comment='Contratos de trabajo de los trabajadores. Incluye información sobre el tipo de contrato, jornada, horas semanales, fechas de inicio y fin, y otros detalles relevantes.'
    )
    op.create_index('contratos_un_activo_por_trabajador_empresa_key', 'contratos', ['empresa_id', 'trabajador_id'], unique=True, postgresql_where=sa.text('activo IS TRUE'))
    op.create_table('festivos',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del festivo.'),
    sa.Column('calendario_id', sa.Uuid(), nullable=False, comment='Identificador del calendario laboral al que pertenece el festivo.'),
    sa.Column('fecha', sa.Date(), nullable=False, comment='Fecha del festivo.'),
    sa.Column('tipo', sa.Enum('Local', 'Autonómico', 'Nacional', name='tipo_festivo_enum'), server_default=sa.text("'Local'::tipo_festivo_enum"), nullable=False, comment='Tipo de festivo.'),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si el festivo está activo.'),
    sa.Column('descripcion', sa.String(length=255), nullable=True, comment='Descripción del festivo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de creación del festivo.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha de actualización del festivo.'),
    sa.ForeignKeyConstraint(['calendario_id'], ['calendarios_laborales.id'], name='festivos_calendario_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='festivos_pkey'),
    sa.UniqueConstraint('calendario_id', 'fecha', name='festivos_calendario_id_fecha_key'),
    comment='Festivos asociados a calendarios laborales.'
    )
    op.create_table('fichajes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del fichaje.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el fichaje.'),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False, comment='Identificador del trabajador al que pertenece el fichaje.'),
    sa.Column('centro_trabajo_id', sa.Uuid(), nullable=False, comment='Identificador del centro de trabajo donde se registró el fichaje.'),
    sa.Column('dispositivo_id', sa.Uuid(), nullable=True, comment='Identificador del dispositivo desde el que se realizó el fichaje, si aplica.'),
    sa.Column('fichaje_sustituido_id', sa.Uuid(), nullable=True, comment='Identificador del fichaje que se sustituye, si aplica.'),
    sa.Column('motivo_pausa_id', sa.Uuid(), nullable=True, comment='Identificador del motivo de la pausa, si aplica.'),
    sa.Column('tipo_evento', sa.Enum('Entrada', 'Salida', 'Inicio_pausa', 'Fin_pausa', name='tipo_evento_fichaje_enum'), server_default=sa.text("'Entrada'::tipo_evento_fichaje_enum"), nullable=False, comment='Tipo fijo del evento de fichaje.'),
    sa.Column('metodo_fichaje', sa.Enum('App_móvil', 'Terminal_rfid', 'Terminal_pin', 'Lector_qr', 'Web', 'Geolocalización', 'Manual', name='metodo_fichaje_enum'), server_default=sa.text("'Manual'::metodo_fichaje_enum"), nullable=False, comment='Método de fichaje.'),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False, comment='Instante oficial del fichaje (referencia legal).'),
    sa.Column('fecha_hora_dispositivo', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora declarada por el dispositivo al registrar el evento.'),
    sa.Column('origen', sa.Enum('Trabajador', 'Corrección_rrhh', 'Sistema', name='origen_fichaje_enum'), server_default=sa.text("'Trabajador'::origen_fichaje_enum"), nullable=False, comment='Origen del fichaje.'),
    sa.Column('estado', sa.Enum('Válido', 'Pendiente_revisión', name='estado_fichaje_enum'), server_default=sa.text("'Válido'::estado_fichaje_enum"), nullable=False, comment='Estado del fichaje.'),
    sa.Column('latitud', sa.Numeric(precision=9, scale=6), nullable=True, comment='Latitud geográfica del fichaje, si aplica.'),
    sa.Column('longitud', sa.Numeric(precision=9, scale=6), nullable=True, comment='Longitud geográfica del fichaje, si aplica.'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Dirección IP desde la que se realizó el fichaje, si aplica.'),
    sa.Column('observaciones', sa.Text(), nullable=True, comment='Observaciones adicionales sobre el fichaje.'),
    sa.Column('firma_digital', sa.Text(), nullable=False, comment='Firma digitalizada obligatoria en Base64 o URL del archivo.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Momento real de inserción en el sistema (no editable); es la prueba temporal frente a fecha_hora, que puede haberse fijado manualmente en una corrección.'),
    sa.Column('hash_integridad', sa.String(length=64), nullable=False, comment='SHA-256 calculado automáticamente sobre los campos clave del registro (ver trigger calcular_hash_fichaje), para evidenciar manipulación.'),
    sa.CheckConstraint("latitud >= '-90'::integer::numeric AND latitud <= 90::numeric", name='fichajes_latitud_check'),
    sa.CheckConstraint("longitud >= '-180'::integer::numeric AND longitud <= 180::numeric", name='fichajes_longitud_check'),
    sa.ForeignKeyConstraint(['empresa_id', 'centro_trabajo_id'], ['centros_trabajo.empresa_id', 'centros_trabajo.id'], name='fichajes_empresa_centro_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id', 'dispositivo_id'], ['dispositivos_fichaje.empresa_id', 'dispositivos_fichaje.id'], name='fichajes_empresa_dispositivo_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id', 'trabajador_id', 'fichaje_sustituido_id'], ['fichajes.empresa_id', 'fichajes.trabajador_id', 'fichajes.id'], name='fichajes_sustitucion_mismo_trabajador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id', 'trabajador_id'], ['trabajadores.empresa_id', 'trabajadores.id'], name='fichajes_empresa_trabajador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='fichajes_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['motivo_pausa_id'], ['motivos_pausa.id'], name='fichajes_motivo_pausa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='fichajes_pkey'),
    sa.UniqueConstraint('empresa_id', 'trabajador_id', 'id', name='fichajes_empresa_trabajador_id_key'),
    comment='Registro de jornada. Tabla INMUTABLE (append-only): ver triggers de bloqueo de UPDATE/DELETE más abajo. Cualquier corrección se gestiona en correcciones_fichaje, opcionalmente insertando una nueva fila que referencia fichaje_sustituido_id.'
    )
    op.create_index('idx_fichajes_centro_fecha', 'fichajes', ['centro_trabajo_id', 'fecha_hora'], unique=False)
    op.create_index('idx_fichajes_empresa_fecha', 'fichajes', ['empresa_id', 'fecha_hora'], unique=False)
    op.create_index('idx_fichajes_sustituido', 'fichajes', ['fichaje_sustituido_id'], unique=False, postgresql_where='(fichaje_sustituido_id IS NOT NULL)')
    op.create_index('idx_fichajes_trabajador_fecha', 'fichajes', ['trabajador_id', 'fecha_hora'], unique=False)
    op.create_table('resumenes_jornada',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único del resumen de jornada.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece el resumen.'),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False, comment='Identificador del trabajador al que corresponde el resumen.'),
    sa.Column('fecha', sa.Date(), nullable=False, comment='Fecha del resumen de jornada (solo fecha, sin hora).'),
    sa.Column('minutos_trabajados', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Total de minutos trabajados en la jornada.'),
    sa.Column('minutos_pausa', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Total de minutos de pausa en la jornada.'),
    sa.Column('minutos_extra', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Total de minutos extra trabajados en la jornada.'),
    sa.Column('tiene_incidencias', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Indica si el resumen tiene alguna incidencia.'),
    sa.Column('cerrado', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Indica si el resumen está cerrado.'),
    sa.Column('hora_entrada', sa.DateTime(timezone=True), nullable=True, comment='Hora de entrada del trabajador.'),
    sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True, comment='Hora de salida del trabajador.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del resumen.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del resumen.'),
    sa.ForeignKeyConstraint(['empresa_id', 'trabajador_id'], ['trabajadores.empresa_id', 'trabajadores.id'], name='resumenes_jornada_empresa_trabajador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='resumenes_jornada_empresa_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='resumenes_jornada_pkey'),
    sa.UniqueConstraint('trabajador_id', 'fecha', name='resumenes_jornada_trabajador_id_fecha_key'),
    comment='Tabla de agregados diarios, recalculada por la aplicación (o un job) a partir de v_fichajes_vigentes. No sustituye a fichajes como prueba legal; es una capa de consulta rápida para nómina y cuadros de mando.'
    )
    op.create_index('idx_resumenes_empresa_fecha', 'resumenes_jornada', ['empresa_id', 'fecha'], unique=False)
    op.create_table('asignaciones_turno',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la asignación de turno.'),
    sa.Column('contrato_id', sa.Uuid(), nullable=False, comment='Identificador del contrato en el que se asigna el turno al trabajador.'),
    sa.Column('turno_id', sa.Uuid(), nullable=False, comment='Identificador del turno que se asigna.'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False, comment='Fecha de inicio de la asignación.'),
    sa.Column('fecha_fin', sa.Date(), nullable=True, comment='Fecha de fin de la asignación.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación de la asignación.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización del registro.'),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='asignaciones_turno_check'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], name='asignaciones_turno_contrato_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], name='asignaciones_turno_turno_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='asignaciones_turno_pkey'),
    comment='Asigna un turno a un trabajador durante un periodo de tiempo. Si fecha_fin es NULL, la asignación es indefinida hasta que se asigne otro turno o se desasigne el turno actual.'
    )
    op.create_table('contratos_calendarios',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la relación contrato-calendario.'),
    sa.Column('contrato_id', sa.Uuid(), nullable=False, comment='Identificador del contrato al que pertenece la relación.'),
    sa.Column('calendario_laboral_id', sa.Uuid(), nullable=False, comment='Identificador del calendario laboral asociado.'),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Indica si la relación contrato-calendario se encuentra activa o no'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación de la relación contrato-calendario.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización de la relación contrato-calendario.'),
    sa.ForeignKeyConstraint(['calendario_laboral_id'], ['calendarios_laborales.id'], name='contratos_calendarios_calendario_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], name='contratos_calendarios_contrato_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contratos_calendarios_pkey'),
    sa.UniqueConstraint('contrato_id', 'calendario_laboral_id', name='contratos_calendarios_contrato_calendario_key'),
    comment='Asocia a cada contrato el calendario anual de su centro aplicable a cada año de vigencia.'
    )
    op.create_table('correcciones_fichaje',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Identificador único de la corrección de fichaje.'),
    sa.Column('empresa_id', sa.Uuid(), nullable=False, comment='Identificador de la empresa a la que pertenece la corrección.'),
    sa.Column('trabajador_id', sa.Uuid(), nullable=False, comment='Identificador del trabajador al que corresponde la corrección.'),
    sa.Column('usuario_solicitador_id', sa.Uuid(), nullable=False, comment='Identificador del usuario que solicita la corrección.'),
    sa.Column('usuario_aprobador_id', sa.Uuid(), nullable=True, comment='Identificador del usuario que aprueba la corrección.'),
    sa.Column('fichaje_afectado_id', sa.Uuid(), nullable=True, comment='Identificador del fichaje afectado por la corrección.'),
    sa.Column('tipo_evento', sa.Enum('Entrada', 'Salida', 'Inicio_pausa', 'Fin_pausa', name='tipo_evento_fichaje_enum'), server_default=sa.text("'Entrada'::tipo_evento_fichaje_enum"), nullable=False, comment='Tipo fijo del evento de fichaje de la corrección.'),
    sa.Column('tipo_correccion', sa.Enum('Alta_manual', 'Modificación', 'Anulación', name='tipo_correccion_enum'), server_default=sa.text("'Alta_manual'::tipo_correccion_enum"), nullable=False, comment='Tipo de corrección.'),
    sa.Column('valor_nuevo', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Valor nuevo de la corrección.'),
    sa.Column('valor_anterior', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Valor anterior de la corrección.'),
    sa.Column('estado', sa.Enum('Pendiente', 'Aprobada', 'Rechazada', name='estado_correccion_enum'), server_default=sa.text("'Pendiente'::estado_correccion_enum"), nullable=False, comment='Estado de la corrección.'),
    sa.Column('motivo', sa.String(length=255), nullable=False, comment='Motivo de la corrección.'),
    sa.Column('fecha_solicitud', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la solicitud de la corrección.'),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora de la resolución de la corrección.'),
    sa.Column('firma_solicitante', sa.Text(), nullable=True, comment='Ruta de la firma digital de quien solicita la corrección.'),
    sa.Column('firma_resolutor', sa.Text(), nullable=True, comment='Ruta de la firma digital de quien resuelve la corrección.'),
    sa.ForeignKeyConstraint(['empresa_id', 'trabajador_id', 'fichaje_afectado_id'], ['fichajes.empresa_id', 'fichajes.trabajador_id', 'fichajes.id'], name='correcciones_fichaje_fichaje_mismo_trabajador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id', 'trabajador_id'], ['trabajadores.empresa_id', 'trabajadores.id'], name='correcciones_fichaje_empresa_trabajador_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name='correcciones_fichaje_empresa_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_aprobador_id'], ['usuarios.id'], name='correcciones_fichaje_usuario_aprobador_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_solicitador_id'], ['usuarios.id'], name='correcciones_fichaje_usuario_solicitador_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='correcciones_fichaje_pkey'),
    comment='Flujo auditable de altas manuales, modificaciones y anulaciones de fichajes. Esta tabla SÍ es mutable (estado pasa de pendiente a aprobada/rechazada), a diferencia de fichajes.'
    )
    op.create_index('idx_correcciones_empresa_estado', 'correcciones_fichaje', ['empresa_id', 'estado'], unique=False)
    op.create_index('idx_correcciones_fichaje_afectado', 'correcciones_fichaje', ['fichaje_afectado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_correcciones_fichaje_afectado', table_name='correcciones_fichaje')
    op.drop_index('idx_correcciones_empresa_estado', table_name='correcciones_fichaje')
    op.drop_table('correcciones_fichaje')
    op.drop_table('contratos_calendarios')
    op.drop_table('asignaciones_turno')
    op.drop_index('idx_resumenes_empresa_fecha', table_name='resumenes_jornada')
    op.drop_table('resumenes_jornada')
    op.drop_index('idx_fichajes_trabajador_fecha', table_name='fichajes')
    op.drop_index('idx_fichajes_sustituido', table_name='fichajes', postgresql_where='(fichaje_sustituido_id IS NOT NULL)')
    op.drop_index('idx_fichajes_empresa_fecha', table_name='fichajes')
    op.drop_index('idx_fichajes_centro_fecha', table_name='fichajes')
    op.drop_table('fichajes')
    op.drop_table('festivos')
    op.drop_index('contratos_un_activo_por_trabajador_empresa_key', table_name='contratos', postgresql_where=sa.text('activo IS TRUE'))
    op.drop_table('contratos')
    op.drop_table('ausencias')
    op.drop_index('idx_auditoria_usuario', table_name='auditoria_accesos', postgresql_where='(usuario_id IS NOT NULL)')
    op.drop_index('idx_auditoria_trabajador', table_name='auditoria_accesos', postgresql_where='(trabajador_id IS NOT NULL)')
    op.drop_index('idx_auditoria_empresa_fecha', table_name='auditoria_accesos')
    op.drop_table('auditoria_accesos')
    op.drop_index('usuarios_empresas_empresa_activo_idx', table_name='usuarios_empresas')
    op.drop_table('usuarios_empresas')
    op.drop_table('trabajadores')
    op.drop_table('roles_permisos')
    op.drop_table('dispositivos_fichaje')
    op.drop_table('departamentos')
    op.drop_table('calendarios_laborales')
    op.drop_table('turnos')
    op.drop_index('roles_nombre_global_key', table_name='roles', postgresql_where=sa.text('empresa_id IS NULL'))
    op.drop_index('roles_empresa_nombre_key', table_name='roles', postgresql_where=sa.text('empresa_id IS NOT NULL'))
    op.drop_table('roles')
    op.drop_index('politicas_retencion_unica_por_empresa_key', table_name='politicas_retencion', postgresql_where=sa.text('empresa_id IS NOT NULL'))
    op.drop_index('politicas_retencion_unica_global_key', table_name='politicas_retencion', postgresql_where=sa.text('empresa_id IS NULL'))
    op.drop_table('politicas_retencion')
    op.drop_table('motivos_pausa')
    op.drop_table('licencias')
    op.drop_index('gestorias_empresas_vinculo_activo_key', table_name='gestorias_empresas', postgresql_where=sa.text('activo IS TRUE'))
    op.drop_index('gestorias_empresas_gestoria_activo_idx', table_name='gestorias_empresas')
    op.drop_index('gestorias_empresas_cliente_activo_idx', table_name='gestorias_empresas')
    op.drop_table('gestorias_empresas')
    op.drop_table('centros_trabajo')
    op.drop_index('usuarios_telefono_activo_key', table_name='usuarios', postgresql_where=sa.text('activo IS TRUE'))
    op.drop_index('usuarios_email_activo_key', table_name='usuarios', postgresql_where=sa.text('activo IS TRUE'))
    op.drop_table('usuarios')
    op.drop_table('permisos')
    op.drop_table('empresas')
    # ### end Alembic commands ###